In [3]:
import cv2
import numpy as np 

#ice aktar 
img = cv2.imread("img/card.png")
cv2.imshow("orijinal", img)

width=400
height=500

#kartın 1-2-3-4 noktalarının pait üzerinden kordinatlarını buldum
pts1=np.float32([[137,0],[0,321],[369,99],[230,426]])

#perspektifi çıkaracağım görüntünün kordinatlarını verdim
pts2=np.float32([[0,0],[0,height],[width,0],[width,height]])

#perspektif cıkarıyorum
matrix = cv2.getPerspectiveTransform(pts1,pts2)
print(matrix)


#cevirme islemini yapıyorum
imgOutput=cv2.warpPerspective(img,matrix,(width,height))
cv2.imshow("donusturulmus", imgOutput)

k=cv2.waitKey(0) & 0xFF
if k==27: #esc harf değeri, esc basıldığında pencereler kapansın
    cv2.destroyAllWindows()


[[ 1.49782184e+00  6.39257296e-01 -2.05201592e+02]
 [-5.68347041e-01  1.33188398e+00  7.78635447e+01]
 [ 6.40191178e-05  3.36342741e-05  1.00000000e+00]]
